version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd react_portfolio &&PORT=7984 yarn start"
    ports:
    - "7984:7984"
